spring:
  cloud:
    consul:
      host: consul
      port: 8500
camel:
  component:
    servlet:
      mapping:
        context-path: /rest/*
  springboot:
    name: MyCamel
management:
  endpoint:
    camelroutes:
      enabled: true
      read-only: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,camelroutes,metrics,prometheus
  info:
    camel:
      enabled: true
      verbose: true
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.apache.camel.spring.boot: INFO
    org.apache.camel.impl: INFO
    de.escalon.microservice.camel: INFO