= Microservice Example

Using Consul, Traefik and Camel Spring Boot

== Spring Boot Camel Rest Service

Built upon https://github.com/apache/camel-spring-boot/tree/master/examples/camel-example-spring-boot-rest-openapi[camel-example-spring-boot-rest-openapi].

To build

   mvn clean install
   docker build -t escalon/camel-microservice-rest:latest .


== Traefik-Gateway

Traefik customized with traefik.toml.


To list Traefik commands

    docker run traefik:v1.7 --help

To build

    docker build -t traefik-gateway .

== Registrator

Registers docker containers with Consul using service tags that are evaluated by Traefik.

Add an environment variable SERVICE_TAGS to a container to add tags in Consul. Tags can be used to control how a service is used, e.g. how it should be published by Traefik or scraped by Prometheus.

When started with `-internal` option, it is sufficient when a container's description *exposes* its internal ports to other services to make it accessible to Traefik.

Expose internal ports to other containers in docker-compose:

[source,yaml]
----
    expose:
      - "8080"
----

An alternative is to *publish* the ports on a random port on the docker host by specifying only the container-internal port in docker-compose.yml:

[source,yaml]
----
    ports:
      - "8080"
----

== Prometheus-Metrics

Prometheus customized with prometheus.yml.

To build

    docker build -t prometheus-metrics .

To view Prometheus metrics about itself, enter the following expression in the Prometheus UI and hit execute:

    prometheus_target_interval_length_seconds

Count number of returned time series:

    count(prometheus_target_interval_length_seconds)

Http Requests:

    http_server_requests_seconds_count


== Microservices

To run the microservices setup:

    docker-compose up                  # stop with ctrl+c
    docker-compose up --remove-orphans # remove unused containers
    docker-compose up -d               # run detached or update running stack
    docker-compose up -d --scale rest=2   # scale service
    docker-compose logs -f             # follow logs

|===
|Service |URL

|Consul
|http://localhost:8500

|Traefik
|http://localhost:8080

|Camel Rest
|http://localhost/rest/users

|Prometheus
|http://localhost:9090/graph

|===
