= Microservice Example

Using Consul, Traefik and Camel Spring Boot

== Spring Boot Camel Rest Service

Built upon https://github.com/apache/camel-spring-boot/tree/master/examples/camel-example-spring-boot-rest-openapi[camel-example-spring-boot-rest-openapi].

To build

   mvn clean install
   docker build -t escalon/camel-microservice-rest:latest .


== Traefik-Gateway

Traefik customized with traefik.toml.


To list Traefik commands

    docker run traefik:v1.7 --help

To build

    docker build -t traefik-gateway .

== Registrator

Registers docker containers with Consul using service tags that are evaluated by Traefik.

When started with `-internal` option, it is sufficient when a container's description exposes its internal ports to other services to make it accessible to Traefik.
[source,yaml]
----
    expose:
      - "8080"
----

An alternative is to publish the ports on a random port on the docker host by specifying only the container-internal port:

[source,yaml]
----
    ports:
      - "8080"
----


== Microservices

To run the microservices

    docker-compose up                  # stop with ctrl+c
    docker-compose up --remove-orphans # remove unused containers
    docker-compose up -d               # run detached or update running stack
    docker-compose up --scale rest=2   # scale service
    docker-compose logs -f             # follow logs

|===
|URL |Service

|http://localhost:8500
|Consul

|http://localhost:8080
|Traefik

|http://localhost/rest/users
|Camel Rest

|===
