spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: rest
          uri: lb://rest
          predicates:
            - Path=/rest/**
          filters:
            - RewritePath=/rest/(?<path>.*), /rest/$\{path}